[workspace]
resolver = "2"
members = [
    "ulpx-core",
    "ulpx-ir",
    "ulpx-ingest",
    "ulpx-mapping",
    "ulpx-infer",
    "ulpx-onboard",
    "ulpx-replay",
    "ulpx-serve", "ulpx-e2e",
    "ulpx-postgres",
    "ulpx-parquet",
    "ulpx-object-store",
    "ulpx-opensearch"
, "ulpx-bench"]
